name: Docker Image CI

on:
  push:
    branches: 
      - "*" 
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - '*'
    branches-ignore:
      - 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
