name: Deploy to AWS 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build 

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AWS_HOST}}
        username: ec2-user
        key: ${{ secrets.AWS_SSH }}
        script: |          
          docker compose down
          docker compose up
