name: Deploy to AWS 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug secrets
      run: |
        echo "EC2_HOST=${{ secrets.AWS_HOST }}"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via SSH
      run: |
        scp -r -o StrictHostKeyChecking=no . ec2-user@${{ secrets.AWS_HOST }}:/home/ec2-user/app

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_HOST }} << 'EOF'
          cd /home/ec2-user/app
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
        EOF

