name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
    

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH }}

    - name: Create directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-19-67.eu-north-1.compute.amazonaws.com 'sudo mkdir -p /home/kanbanBE/app && sudo chown -R ubuntu:ubuntu /home/kanbanBE/app'

    - name: Copy files via scp
      run: |
        scp -o StrictHostKeyChecking=no -r * ubuntu@ec2-13-60-19-67.eu-north-1.compute.amazonaws.com:/home/kanbanBE/app

    - name: SSH and deploy
      run: |
        ssh -f -o StrictHostKeyChecking=no ubuntu@ec2-13-60-19-67.eu-north-1.compute.amazonaws.com << 'EOF'
          cd /home/kanbanBE/app
          echo "Stopping existing Docker containers..."
          sudo docker compose down
          echo "Starting Docker containers..."
          sudo docker compose up --build
        EOF 



